name: Build and Release Arch Linux RootFS

on:
  workflow_dispatch:
jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged  # 需要特权模式进行挂载操作

    steps:
    - name: Prepare environment
      run: |
        # 更新系统并安装必要工具
        pacman -Syu --noconfirm --needed arch-install-scripts qemu-user-static

    - name: Initialize pacman keys
      run: |
        # 初始化pacman密钥环
        pacman-key --init
        pacman-key --populate archlinux

    - name: Create rootfs directory
      run: |
        mkdir -p arch-rootfs

    - name: Install base system
      run: |
        # 使用pacstrap安装基础系统
        pacstrap -C /etc/pacman.conf -c arch-rootfs base base-devel
        
    - name: Clean up rootfs
      run: |
        # 清理包缓存
        rm -rf arch-rootfs/var/cache/pacman/pkg/*
        
        # 重置机器ID
        rm -f arch-rootfs/etc/machine-id

    - name: Compress rootfs
      run: |
        # 创建带日期和版本号的压缩包
        VERSION=$(date +%Y%m%d)
        tar -czf arch-rootfs-${VERSION}.tar.gz -C arch-rootfs .

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: arch-rootfs-*.tar.gz
        asset_name: arch-rootfs-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
