name: Build and Release Arch Linux RootFS

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version (e.g. v2023.07)'
        required: true

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置动态版本号
      - name: Set version
        id: set-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=$(echo ${{ github.ref }} | cut -d'/' -f3)" >> $GITHUB_ENV
          fi

      - name: Set up Docker
        run: docker pull archlinux:latest

      - name: Create rootfs directory
        run: mkdir -p rootfs

      - name: Install base system
        run: |
          docker run --rm --privileged \
            -v "$(pwd)/rootfs:/rootfs" \
            archlinux \
            bash -c "pacman -Sy --noconfirm --needed archlinux-keyring arch-install-scripts && \
            pacman -Syu --noconfirm && \
            pacstrap -c -K /rootfs base base-devel"

      - name: Compress rootfs
        run: |
          tar --numeric-owner --xattrs --acls -czvf arch-rootfs-${{ env.VERSION }}.tar.gz -C rootfs .

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: arch-rootfs-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
