name: Build and Release Arch Linux RootFS

on:
  release:
    types: [created]

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker pull archlinux:latest

      - name: Create rootfs directory
        run: mkdir -p rootfs

      - name: Install base system
        run: |
          docker run --rm \
            -v "$(pwd)/rootfs:/rootfs" \
            archlinux \
            bash -c "pacman -Sy --noconfirm --needed archlinux-keyring && \
            pacman -Syu --noconfirm && \
            pacstrap -c -K /rootfs base base-devel"

      - name: Compress rootfs
        run: |
          VERSION=$(echo ${{ github.ref }} | cut -d'/' -f3)
          tar --numeric-owner --xattrs --acls -czvf arch-rootfs-$VERSION.tar.gz -C rootfs .

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: arch-rootfs-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
